//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC [dbo].[uspLoad_GetClinicalReasons_Cor551240415V1]")]
        public string sqlGetClinicalReasons {
            get {
                return ((string)(this["sqlGetClinicalReasons"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC [dbo].[uspGet_PatientSearch_Cor551240415V1]")]
        public string SqlGetPatient {
            get {
                return ((string)(this["SqlGetPatient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[uspLoad_PatientData_Cor551240415V1]")]
        public string SqlLoadNote {
            get {
                return ((string)(this["SqlLoadNote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC [dbo].[uspGet_MaxNoteId_Cor551240415V1] ")]
        public string SqlGetId {
            get {
                return ((string)(this["SqlGetId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uspLoad_SubTables_Cor551240415V1")]
        public string SqlInsertNoteData {
            get {
                return ((string)(this["SqlInsertNoteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC [dbo].[uspGet_RetrievePatData_Cor551240415V1]")]
        public string SqlRetrieveData {
            get {
                return ((string)(this["SqlRetrieveData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uspLoad_SignedNote_Cor551240415V1")]
        public string SqlSignNote {
            get {
                return ((string)(this["SqlSignNote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uspLoad_UpdateForm_Cor551240415V1")]
        public string SqlUpdateForm {
            get {
                return ((string)(this["SqlUpdateForm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uspRemove_SignedNoteValue_Cor551240415V1")]
        public string SqlRemoveSign {
            get {
                return ((string)(this["SqlRemoveSign"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC [dbo].[uspGet_AuditData_Cor551240415V1]")]
        public string SqlAuditData {
            get {
                return ((string)(this["SqlAuditData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uspLoad_UpdateAuditData_Cor551240415V1")]
        public string SqlUpdateAuditData {
            get {
                return ((string)(this["SqlUpdateAuditData"]));
            }
        }
    }
}
